global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'view-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['view-server:8080']
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'mock-data-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mock-data-generator:8080']
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 15s 